project:
  name: start
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingjdbc.yml
#
#  datasource:
##    driver-class-name: org.postgresql.Driver
##    password: mybbs
##    url: jdbc:postgresql://10.199.97.142:5432/mybbs
##    username: mybbs
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      # 数据库
#      url: jdbc:postgresql://10.199.97.142:5432/mybbs
#      username: mybbs
#      password: mybbs
#      driver-class-name: org.postgresql.Driver
#      # 连接池-初始化大小
#      initial-size: 10
#      # 连接池-最大连接数
#      max-active: 100
#      # 最大等待时间
#      max-wait: 60000
#      # 连接池-最小空闲数
#      min-idle: 10
#      # 检测空闲连接
#      test-while-idle: true
#      # 最小空闲时间
#      min-evictable-idle-time-millis: 300000
  flyway:
    url: jdbc:postgresql://10.199.97.142:5432/mybbs
    schemas: public
    user: "mybbs"
    password: "mybbs"
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration/prod

# 具体属性参见
# https://mybatis.org/mybatis-3/zh/configuration.html
# https://baomidou.com/pages/56bac0/#mapperlocations
# 不再采用 config-location: classpath:mybatis/mybatis-config.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperLocations: classpath*:mybatis/mapper/*mapper.xml
  mapUnderscoreToCamelCase: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger/index.html

